/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "SW_aliases.h"
#include "SW.h"
#include "VRx_aliases.h"
#include "VRx.h"
#include "Clock_1.h"
#include "UART.h"
#include "VRy_aliases.h"
#include "VRy.h"
#include "CAN.h"
#include "TX_aliases.h"
#include "TX.h"
#include "RX_aliases.h"
#include "RX.h"
#include "PWM_L1.h"
#include "Clock_2.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "PWM_L2.h"
#include "Control_LED1.h"
#include "ADC_SAR.h"
#include "ADC_IntClock.h"
#include "ADC_TempBuf_dma.h"
#include "ADC_FinalBuf_dma.h"
#include "ADC_IRQ.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

