/*****************************************************************************
* Model: remotecontrol.qm
* File:  ./remotecontrol.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::remotecontrol.h} ....................................................*/
/*****************************************************************************
* Company : Yantronix
* Author  : Satish Nair
* Mailto  : satishgn77@gmail.com
*****************************************************************************/

#ifndef remotecontrol_h
#define remotecontrol_h

enum RemoteControlSignals {
    RESERVE_SIG = Q_USER_SIG,
    LED_FLASH_SIG,
    SW_CHANGE_SIG,
    ADC_SAMPLE_SIG,
    CAN_RECEIVE_SIG,
    TERMINATE_SIG,
    MAX_SIG
};

extern struct RemoteControl AO_RemoteControl;

/*${AOs::RemoteControl_ctor} ...............................................*/
void RemoteControl_ctor(void);


#endif /* remotecontrol_h */
