/*****************************************************************************
* Model: remotecontrol.qm
* File:  ./remotecontrol.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::remotecontrol.c} ....................................................*/
/*****************************************************************************
* Company : Yantronix
* Author  : Satish Nair
* Mailto  : satishgn77@gmail.com
*****************************************************************************/

#include "qpn.h"
#include "bsp.h"
#include "remotecontrol.h"
#include <stdio.h>

Q_DEFINE_THIS_MODULE("remotecontrol")

#define INIT_WAIT_TOUT         (QTimeEvtCtr)(BSP_TICKS_PER_SEC / 10U)
#define ADC_SAMPLE_TOUT        (QTimeEvtCtr)(BSP_TICKS_PER_SEC / 10U)


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 5.8.0 or higher required
#endif

/*${AOs::RemoteControl} ....................................................*/
typedef struct RemoteControl {
/* protected: */
    QActive super;

/* private: */
    volatile int16_t J1_VRx_Mid;
    volatile int16_t J1_VRy_Mid;
    volatile int16_t J1_VRx_Max;
    volatile int16_t J1_VRy_Max;
    volatile int16_t J1_VRx_Out;
    volatile int16_t J1_VRy_Out;
    volatile uint8_t switchState;
    uint16_t PWM_Compare;
    char_t txData[TX_DATA_SIZE];
} RemoteControl;

/* protected: */
static QState RemoteControl_initial(RemoteControl * const me);
static QState RemoteControl_operational(RemoteControl * const me);
static QState RemoteControl_swChanged(RemoteControl * const me);
static QState RemoteControl_canMsgReceived(RemoteControl * const me);
static QState RemoteControl_initWaiting(RemoteControl * const me);
static QState RemoteControl_ledFlashing(RemoteControl * const me);
static QState RemoteControl_adcSampling(RemoteControl * const me);


/*${AOs::AO_RemoteControl} .................................................*/
struct RemoteControl AO_RemoteControl;

/*${AOs::RemoteControl_ctor} ...............................................*/
void RemoteControl_ctor(void) {
    RemoteControl *me = &AO_RemoteControl;
    QActive_ctor(&me->super, Q_STATE_CAST(&RemoteControl_initial));
    me->J1_VRx_Mid = me->J1_VRx_Max = me->J1_VRx_Out = 0;
    me->J1_VRy_Mid = me->J1_VRy_Max = me->J1_VRy_Out = 0;
    me->switchState = SWITCH_RELEASED;
    me->PWM_Compare = 0;
}
/*${AOs::RemoteControl} ....................................................*/
/*${AOs::RemoteControl::SM} ................................................*/
static QState RemoteControl_initial(RemoteControl * const me) {
    /* ${AOs::RemoteControl::SM::initial} */
    return Q_TRAN(&RemoteControl_operational);
}
/*${AOs::RemoteControl::SM::operational} ...................................*/
static QState RemoteControl_operational(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational} */
        case Q_EXIT_SIG: {
            QActive_disarmX(&me->super, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&RemoteControl_initWaiting);
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::SW_CHANGE} */
        case SW_CHANGE_SIG: {
            status_ = Q_TRAN(&RemoteControl_swChanged);
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::ADC_SAMPLE} */
        case ADC_SAMPLE_SIG: {
            status_ = Q_TRAN(&RemoteControl_adcSampling);
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::LED_FLASH} */
        case LED_FLASH_SIG: {
            status_ = Q_TRAN(&RemoteControl_ledFlashing);
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::CAN_RECEIVE} */
        case CAN_RECEIVE_SIG: {
            status_ = Q_TRAN(&RemoteControl_canMsgReceived);
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            //QACTIVE_POST(&AO_RemoteControl, ADC_SAMPLE_SIG, 0U);
            status_ = Q_TRAN(&RemoteControl_adcSampling);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::RemoteControl::SM::operational::swChanged} ........................*/
static QState RemoteControl_swChanged(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational::swChanged} */
        case Q_ENTRY_SIG: {
            /* Store the current switch state */
            me->switchState = (uint8_t)Q_PAR(me);

            /* Send CAN message with switch state */
            BSP_sendCANMsgJ1SWData(me->switchState);

            if (me->switchState == SWITCH_PRESSED)
            {
                BSP_printString("switch pressed.\r\n");
            }


            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&RemoteControl_operational);
            break;
        }
    }
    return status_;
}
/*${AOs::RemoteControl::SM::operational::canMsgReceived} ...................*/
static QState RemoteControl_canMsgReceived(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational::canMsgReceived} */
        case Q_ENTRY_SIG: {
            me->PWM_Compare = (uint16_t)Q_PAR(me);
            BSP_setLedPWM(me->PWM_Compare);

            sprintf(me->txData, "PWM pulse width: %hu \r\n", me->PWM_Compare);
            BSP_printString(me->txData);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&RemoteControl_operational);
            break;
        }
    }
    return status_;
}
/*${AOs::RemoteControl::SM::operational::initWaiting} ......................*/
static QState RemoteControl_initWaiting(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational::initWaiting} */
        case Q_ENTRY_SIG: {
            QActive_armX((QActive *)me, 0U, INIT_WAIT_TOUT, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::initWaiting} */
        case Q_EXIT_SIG: {
            me->J1_VRx_Mid = BSP_getADCResult(ADC_CHANNEL_NUMBER_0);
            me->J1_VRy_Mid = BSP_getADCResult(ADC_CHANNEL_NUMBER_1);

            me->J1_VRx_Max = me->J1_VRy_Max = 4095;

            QActive_armX((QActive *)me, 0U, ADC_SAMPLE_TOUT, ADC_SAMPLE_TOUT);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::initWaiting::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&RemoteControl_ledFlashing);
            break;
        }
        default: {
            status_ = Q_SUPER(&RemoteControl_operational);
            break;
        }
    }
    return status_;
}
/*${AOs::RemoteControl::SM::operational::ledFlashing} ......................*/
static QState RemoteControl_ledFlashing(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational::ledFlashing} */
        case Q_ENTRY_SIG: {
            BSP_ledFlash();
            QACTIVE_POST(&AO_RemoteControl, ADC_SAMPLE_SIG, 0U);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&RemoteControl_operational);
            break;
        }
    }
    return status_;
}
/*${AOs::RemoteControl::SM::operational::adcSampling} ......................*/
static QState RemoteControl_adcSampling(RemoteControl * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::RemoteControl::SM::operational::adcSampling} */
        case Q_ENTRY_SIG: {
            if (BSP_isADCEOC()) {
                /* Gets ADC conversion result */
                me->J1_VRx_Out = BSP_getADCResult(ADC_CHANNEL_NUMBER_0);
                me->J1_VRy_Out = BSP_getADCResult(ADC_CHANNEL_NUMBER_1);

                /* Saturates ADC result to positive numbers */
                if (me->J1_VRx_Out < 0)
                {
                    me->J1_VRx_Out = 0;
                }

                if (me->J1_VRy_Out < 0)
                {
                    me->J1_VRy_Out = 0;
                }

                /* Sends value of ADC output via CAN */
                BSP_sendCANMsgJ1VRxData(me->J1_VRx_Mid, me->J1_VRx_Max, me->J1_VRx_Out);
                BSP_sendCANMsgJ1VRyData(me->J1_VRy_Mid, me->J1_VRy_Max, me->J1_VRy_Out);

                sprintf(me->txData, "VRx: %u, VRy: %u \r\n", me->J1_VRx_Out, me->J1_VRy_Out);
                BSP_printString(me->txData);
            }
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::RemoteControl::SM::operational::adcSampling::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            //QACTIVE_POST(&AO_RemoteControl, LED_FLASH_SIG, 0U);
            status_ = Q_TRAN(&RemoteControl_ledFlashing);
            break;
        }
        default: {
            status_ = Q_SUPER(&RemoteControl_operational);
            break;
        }
    }
    return status_;
}


