/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "TX.h"
#include "TX_aliases.h"
#include "CAN.h"
#include "Clock_1.h"
#include "M1_ENA.h"
#include "M1_ENA_aliases.h"
#include "PWM_M1.h"
#include "RX.h"
#include "RX_aliases.h"
#include "M1_IN1.h"
#include "M1_IN1_aliases.h"
#include "M1_IN2.h"
#include "M1_IN2_aliases.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "PWM_L1.h"
#include "PWM_L2.h"
#include "Clock_2.h"
#include "Control_LED1.h"
#include "M2_ENB.h"
#include "M2_ENB_aliases.h"
#include "PWM_M2.h"
#include "M2_IN3.h"
#include "M2_IN3_aliases.h"
#include "M2_IN4.h"
#include "M2_IN4_aliases.h"
#include "M3_ENA.h"
#include "M3_ENA_aliases.h"
#include "PWM_M3.h"
#include "M3_IN1.h"
#include "M3_IN1_aliases.h"
#include "M3_IN2.h"
#include "M3_IN2_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

